#
# The Flash Memory Controller v100 Device Driver for vendor
#
# Copyright (c) 2016 HiSilicon (Shanghai) Technologies Co., Ltd.
#
# This program is free software; you can redistribute  it and/or modify it
# under  the terms of  the GNU General  Public License as published by the
# Free Software Foundation;  either version 2 of the  License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

#
# drivers/mtd/nand/fmc100_nand/Makefile
#

obj-$(CONFIG_MTD_NAND_FMC100) += fmc100_nand.o
fmc100_nand-objs :=  fmc_nand_spl_ids.o fmc100_nand_os.o

