#
# The Flash Memory Controller v100 Device Driver for vendor
#
# Copyright (c) 2016-2017 HiSilicon (Shanghai) Technologies Co., Ltd.
#
# This program is free software; you can redistribute  it and/or modify it
# under  the terms of  the GNU General  Public License as published by the
# Free Software Foundation;  either version 2 of the  License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#

#
# drivers/mtd/nand/fmc100/Makefile
#

obj-$(CONFIG_MTD_SPI_NAND_FMC100) += fmc100_spi_nand.o

fmc100_spi_nand-objs := fmc100_os.o fmc100.o fmc_spi_nand_ids.o fmc100_spi_general.o
