# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_HI3xxx) += \
	hi3620-hi4511.dtb
dtb-$(CONFIG_ARCH_HIP01) += \
	hip01-ca9x2.dtb
dtb-$(CONFIG_ARCH_HIP04) += \
	hip04-d01.dtb
dtb-$(CONFIG_ARCH_HISI) += \
	hi3519-demb.dtb
dtb-$(CONFIG_ARCH_HIX5HD2) += \
	hisi-x5hd2-dkb.dtb
dtb-$(CONFIG_ARCH_SD5203) += \
	sd5203.dtb
dtb-$(CONFIG_ARCH_HI3516EV200) += hi3516ev200-demb.dtb
dtb-$(CONFIG_ARCH_HI3516EV300) += hi3516ev300-demb.dtb
dtb-$(CONFIG_ARCH_HI3518EV300) += hi3518ev300-demb.dtb
dtb-$(CONFIG_ARCH_HI3516DV200) += hi3516dv200-demb.dtb
dtb-$(CONFIG_ARCH_HI3516DV300) += hi3516dv300-demb.dtb
